<?xml version="1.0" encoding="utf-8"?><Database Name="ELDB" Class="MASDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=wnl;Initial Catalog=ELDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ELDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Division" Member="Divisions">
    <Type Name="Division">
      <Column Name="Division_code" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Division_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Division_status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="user_card" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Column Name="user_mobile" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="user_email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="user_type" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="user_state" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="user_status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>