#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ELDB")]
	public partial class MASDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDivision(Division instance);
    partial void UpdateDivision(Division instance);
    partial void DeleteDivision(Division instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public MASDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ELDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MASDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MASDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MASDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MASDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Division> Divisions
		{
			get
			{
				return this.GetTable<Division>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Division")]
	public partial class Division : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Division_code;
		
		private string _Division_name;
		
		private char _Division_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDivision_codeChanging(string value);
    partial void OnDivision_codeChanged();
    partial void OnDivision_nameChanging(string value);
    partial void OnDivision_nameChanged();
    partial void OnDivision_statusChanging(char value);
    partial void OnDivision_statusChanged();
    #endregion
		
		public Division()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_code", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Division_code
		{
			get
			{
				return this._Division_code;
			}
			set
			{
				if ((this._Division_code != value))
				{
					this.OnDivision_codeChanging(value);
					this.SendPropertyChanging();
					this._Division_code = value;
					this.SendPropertyChanged("Division_code");
					this.OnDivision_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Division_name
		{
			get
			{
				return this._Division_name;
			}
			set
			{
				if ((this._Division_name != value))
				{
					this.OnDivision_nameChanging(value);
					this.SendPropertyChanging();
					this._Division_name = value;
					this.SendPropertyChanged("Division_name");
					this.OnDivision_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_status", DbType="Char(1) NOT NULL")]
		public char Division_status
		{
			get
			{
				return this._Division_status;
			}
			set
			{
				if ((this._Division_status != value))
				{
					this.OnDivision_statusChanging(value);
					this.SendPropertyChanging();
					this._Division_status = value;
					this.SendPropertyChanged("Division_status");
					this.OnDivision_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_id;
		
		private string _user_name;
		
		private string _user_card;
		
		private string _user_mobile;
		
		private string _user_email;
		
		private System.Nullable<char> _user_type;
		
		private System.Nullable<char> _user_state;
		
		private System.Nullable<char> _user_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_cardChanging(string value);
    partial void Onuser_cardChanged();
    partial void Onuser_mobileChanging(string value);
    partial void Onuser_mobileChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_typeChanging(System.Nullable<char> value);
    partial void Onuser_typeChanged();
    partial void Onuser_stateChanging(System.Nullable<char> value);
    partial void Onuser_stateChanged();
    partial void Onuser_statusChanging(System.Nullable<char> value);
    partial void Onuser_statusChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_card", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string user_card
		{
			get
			{
				return this._user_card;
			}
			set
			{
				if ((this._user_card != value))
				{
					this.Onuser_cardChanging(value);
					this.SendPropertyChanging();
					this._user_card = value;
					this.SendPropertyChanged("user_card");
					this.Onuser_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_mobile", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_mobile
		{
			get
			{
				return this._user_mobile;
			}
			set
			{
				if ((this._user_mobile != value))
				{
					this.Onuser_mobileChanging(value);
					this.SendPropertyChanging();
					this._user_mobile = value;
					this.SendPropertyChanged("user_mobile");
					this.Onuser_mobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="VarChar(20)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="Char(1)")]
		public System.Nullable<char> user_type
		{
			get
			{
				return this._user_type;
			}
			set
			{
				if ((this._user_type != value))
				{
					this.Onuser_typeChanging(value);
					this.SendPropertyChanging();
					this._user_type = value;
					this.SendPropertyChanged("user_type");
					this.Onuser_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_state", DbType="Char(1)")]
		public System.Nullable<char> user_state
		{
			get
			{
				return this._user_state;
			}
			set
			{
				if ((this._user_state != value))
				{
					this.Onuser_stateChanging(value);
					this.SendPropertyChanging();
					this._user_state = value;
					this.SendPropertyChanged("user_state");
					this.Onuser_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_status", DbType="Char(1)")]
		public System.Nullable<char> user_status
		{
			get
			{
				return this._user_status;
			}
			set
			{
				if ((this._user_status != value))
				{
					this.Onuser_statusChanging(value);
					this.SendPropertyChanging();
					this._user_status = value;
					this.SendPropertyChanged("user_status");
					this.Onuser_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
